In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import sqlite3
from sqlite3 import Error

#change your file path
homeless = pd.read_csv('C:/Users/sspet/Downloads/homeless_impact.csv')
print(homeless.head())
print(homeless['county'].nunique())
print(homeless['county'].value_counts())

#change your file path
hospital = pd.read_csv('C:/Users/sspet/Downloads/hospitals_by_county.csv')
print(hospital.head())

      county        date  rooms  rooms_occupied  trailers_requested  \
0    Alameda  2020-04-14  403.0           115.0                91.0
1     Alpine  2020-04-14    NaN             NaN                 NaN
2     Amador  2020-04-14    NaN             NaN                 NaN
3      Butte  2020-04-14   65.0            65.0                 NaN
4  Calaveras  2020-04-14    NaN             NaN                 NaN

   trailers_delivered  donated_trailers_delivered
0                85.0                         NaN
1                 NaN                         NaN
2                 NaN                         NaN
3                 NaN                         NaN
4                 NaN                         NaN
173
San Francisco            167
Monterey County          156
Kern County              156
Kings County             156
Orange County            156
Inyo County              156
Colusa County            156
Yuba County              156
Del Norte County         156
Sacramento County        156
Lake County              156
Calaveras County         156
El Dorado County         156
Los Angeles County       156
Alameda County           156
Riverside County         156
Madera County            156
Amador County            156
Trinity County           156
Contra Costa County      156
Butte County             156
Tuolumne County          156
Stanislaus County        156
Santa Cruz County        156
Mono County              156
Sutter County            156
San BernardinoÂ County    156
San Benito County        156
Solano County            156
Modoc County             156
                        ...
Modoc                      1
Mendocino                  1
Plumas                     1
Ventura                    1
Trinity                    1
Santa Cruz                 1
Wilton Rancheria           1
Yuba                       1
Lassen                     1
Orange                     1
Riverside                  1
Calaveras                  1
Butte                      1
Siskiyou                   1
Alameda                    1
San Bernardino             1
Contra Costa               1
Del Norte                  1
San Luis Obispo            1
Merced                     1
Fresno                     1
Monterey                   1
El Dorado                  1
Sonoma                     1
Sacramento                 1
San Diego                  1
Santa Clara                1
Nevada                     1
Sutter                     1
San Mateo                  1
Name: county, Length: 173, dtype: int64
      county todays_date  hospitalized_covid_confirmed_patients  \
0  Mendocino  2020-03-29                                    1.0
1     Orange  2020-03-29                                   74.0
2    Alameda  2020-03-29                                   36.0
3   Siskiyou  2020-03-29                                    0.0
4  Del Norte  2020-03-29                                    1.0

   hospitalized_suspected_covid_patients  hospitalized_covid_patients  \
0                                   11.0                          NaN
1                                  167.0                          NaN
2                                   91.0                          NaN
3                                    0.0                          NaN
4                                    2.0                          NaN

   all_hospital_beds  icu_covid_confirmed_patients  \
0                NaN                           0.0
1                NaN                          31.0
2                NaN                          20.0
3                NaN                           0.0
4                NaN                           0.0

   icu_suspected_covid_patients  icu_available_beds
0                           0.0                 1.0
1                          40.0               131.0
2                          16.0               119.0
3                           0.0                 2.0
4                           0.0                 3.0

In [ ]:
db_list = []
key = 0
for row_name, item in homeless.iterrows():
    temp = []
    temp.append(str(key))
    for x in item:
        temp.append(x)
    db_list.append(temp)
    key = key+1
#print(db_list)

In [ ]:
def create_connection(db_file, delete_db=False):
    import os
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        conn.execute("PRAGMA foreign_keys = 1")
    except Error as e:
        print(e)

    return conn


def create_table(conn, create_table_sql):
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)
        
def execute_sql_statement(sql_statement, conn):
    cur = conn.cursor()
    cur.execute(sql_statement)

    rows = cur.fetchall()

    
    return rows

In [23]:
def insert_homeless(conn, values):
    sql = """ INSERT INTO HOMELESS VALUES(?,?,?,?,?,?,?,?)"""
    cur = conn.cursor()
    #print(values)
    cur.execute(sql, values)
    return cur.lastrowid

create_homeless_table_sql = """CREATE TABLE [HOMELESS] (
    [PK] TEXT NOT NULL PRIMARY KEY,
    [COUNTY] TEXT NOT NULL,
    [DATE] TEXT NOT NULL,
    [ROOMS] FLOAT,
    [ROOM_OCCUPIED] FLOAT,
    [TRAILERS_REQUESTED] FLOAT,
    [TRAILERS_DELIVERED] FLOAT,
    [DONATED_TRAILERS_DELIVERED] FLOAT
    );"""

db_file = 'myfile'
conn = create_connection(db_file)
with conn:
    create_table(conn, create_homeless_table_sql)
    for ele in db_list:
        insert_homeless(conn, ele)
sql_statement = "select * FROM HOMELESS"
df = pd.read_sql_query(sql_statement, conn)
display(df)

,PK,COUNTY,DATE,ROOMS,ROOM_OCCUPIED,TRAILERS_REQUESTED,TRAILERS_DELIVERED,DONATED_TRAILERS_DELIVERED
0,0,Alameda,2020-04-14,403.0,115.0,91.0,85.0,NaN
1,1,Alpine,2020-04-14,NaN,NaN,NaN,NaN,NaN
2,2,Amador,2020-04-14,NaN,NaN,NaN,NaN,NaN
3,3,Butte,2020-04-14,65.0,65.0,NaN,NaN,NaN
4,4,Calaveras,2020-04-14,NaN,NaN,NaN,NaN,NaN
5,5,Colusa,2020-04-14,NaN,NaN,NaN,NaN,NaN
6,6,Contra Costa,2020-04-14,340.0,NaN,NaN,NaN,NaN
7,7,Del Norte,2020-04-14,NaN,NaN,NaN,NaN,NaN
8,8,El Dorado,2020-04-14,NaN,NaN,NaN,NaN,NaN
9,9,Fresno,2020-04-14,305.0,250.0,28.0,NaN,NaN
10,10,Glenn,2020-04-14,NaN,NaN,NaN,NaN,NaN
11,11,Humboldt,2020-04-14,NaN,NaN,15.0,NaN,NaN
12,12,Imperial,2020-04-14,36.0,NaN,NaN,NaN,NaN
13,13,Inyo,2020-04-14,NaN,NaN,NaN,NaN,NaN
14,14,Kern,2020-04-14,NaN,NaN,15.0,15.0,NaN
15,15,Kings,2020-04-14,NaN,NaN,NaN,NaN,NaN
16,16,Lake,2020-04-14,NaN,NaN,NaN,NaN,NaN
17,17,Lassen,2020-04-14,NaN,NaN,NaN,NaN,NaN
18,18,Los Angeles,2020-04-14,2654.0,535.0,658.0,654.0,NaN
19,19,Madera,2020-04-14,NaN,NaN,NaN,NaN,NaN
20,20,Marin,2020-04-14,80.0,43.0,44.0,NaN,NaN
21,21,Mariposa,2020-04-14,44.0,NaN,NaN,NaN,NaN
22,22,Mendocino,2020-04-14,103.0,63.0,NaN,NaN,NaN
23,23,Merced,2020-04-14,NaN,NaN,NaN,NaN,NaN
24,24,Mono,2020-04-14,48.0,NaN,NaN,NaN,NaN
25,25,Modoc,2020-04-14,NaN,NaN,NaN,NaN,NaN
26,26,Monterey,2020-04-14,NaN,NaN,108.0,NaN,NaN
27,27,Napa,2020-04-14,NaN,NaN,18.0,NaN,NaN
28,28,Nevada,2020-04-14,27.0,NaN,NaN,NaN,NaN
29,29,Orange,2020-04-14,276.0,NaN,78.0,74.0,NaN
...,...,...,...,...,...,...,...,...
9963,9963,Placer County,2020-11-19,68.0,56.0,12.0,12.0,NaN
9964,9964,Plumas County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9965,9965,Riverside County,2020-11-19,235.0,235.0,15.0,15.0,NaN
9966,9966,Sacramento County,2020-11-19,382.0,361.0,63.0,63.0,NaN
9967,9967,San Benito County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9968,9968,San BernardinoÂ County,2020-11-19,427.0,427.0,20.0,NaN,20.0
9969,9969,San Diego County,2020-11-19,784.0,54.0,44.0,44.0,NaN
9970,9970,San Francisco,2020-11-19,2731.0,2021.0,91.0,91.0,NaN
9971,9971,San Joaquin County,2020-11-19,73.0,63.0,NaN,NaN,NaN
9972,9972,San Luis Obispo County,2020-11-19,155.0,NaN,14.0,14.0,NaN
9973,9973,San Mateo County,2020-11-19,164.0,164.0,NaN,NaN,NaN
9974,9974,Santa Barbara County,2020-11-19,95.0,56.0,NaN,NaN,NaN
9975,9975,Santa Clara County,2020-11-19,837.0,590.0,105.0,12.0,NaN
9976,9976,Santa Cruz County,2020-11-19,266.0,184.0,35.0,NaN,12.0
9977,9977,Shasta County,2020-11-19,97.0,92.0,NaN,NaN,NaN
9978,9978,Sierra County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9979,9979,Siskiyou County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9980,9980,Solano County,2020-11-19,126.0,114.0,NaN,NaN,NaN
9981,9981,Sonoma County,2020-11-19,133.0,86.0,24.0,24.0,NaN
9982,9982,Stanislaus County,2020-11-19,136.0,70.0,NaN,NaN,NaN
9983,9983,Sutter County,2020-11-19,16.0,16.0,NaN,NaN,NaN
9984,9984,Tehama County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9985,9985,Trinity County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9986,9986,Tulare County,2020-11-19,133.0,84.0,NaN,NaN,NaN
9987,9987,Tuolumne County,2020-11-19,21.0,21.0,NaN,NaN,NaN
9988,9988,Ventura County,2020-11-19,370.0,191.0,NaN,NaN,NaN
9989,9989,Yolo County,2020-11-19,157.0,147.0,NaN,NaN,NaN
9990,9990,Yuba County,2020-11-19,NaN,NaN,NaN,NaN,NaN
9991,9991,Wilton Rancheria Tribe,2020-11-19,NaN,NaN,NaN,NaN,NaN
9992,9992,Bishop Paiute Tribal Council,2020-11-19,NaN,NaN,NaN,NaN,NaN

In [24]:
create_hospital_table_sql = """CREATE TABLE [HOSPITAL] (
    [PK] TEXT NOT NULL PRIMARY KEY,
    [COUNTY] TEXT NOT NULL,
    [DATE] TEXT NOT NULL,
    [HOSPITALIZED_COVID_CONFIRMED_PATIENTS] INTEGER,
    [HOSPITALIZED_SUSPECTED_COVID_PATIENTS] INTEGER,
    [HOSPITALIZED_COVID_PATIENTS] INTEGER,
    [ALL_HOSPITAL_BEDS] INTEGER,
    [ICU_COVID_CONFIRMED_PATIENTS] INTEGER,
    [ICU_SUSPECTED_COVID_PATIENTS] INTEGER,
    [ICU_AVAILABLE_BEDS] INTEGER
    );"""   


def insert_hospital(conn, values):
    sql = """ INSERT INTO HOSPITAL VALUES(?,?,?,?,?,?,?,?,?,?)"""
    cur = conn.cursor()
    #print(values)
    cur.execute(sql, values)
    return cur.lastrowid

db_list2 = []
key = 0
for row_name, item in hospital.iterrows():
    temp = []
    temp.append(str(key))
    for x in item:
        temp.append(x)
    db_list2.append(temp)
    key += 1
   
    
conn = create_connection(db_file, True)
with conn:
    create_table(conn, create_hospital_table_sql)
    for ele in db_list2:
        insert_hospital(conn, ele)

In [25]:
sql_statement = "select * FROM Hospital"
df = pd.read_sql_query(sql_statement, conn)
display(df)

,PK,COUNTY,DATE,HOSPITALIZED_COVID_CONFIRMED_PATIENTS,HOSPITALIZED_SUSPECTED_COVID_PATIENTS,HOSPITALIZED_COVID_PATIENTS,ALL_HOSPITAL_BEDS,ICU_COVID_CONFIRMED_PATIENTS,ICU_SUSPECTED_COVID_PATIENTS,ICU_AVAILABLE_BEDS
0,0,Mendocino,2020-03-29,1.0,11.0,NaN,NaN,0.0,0.0,1.0
1,1,Orange,2020-03-29,74.0,167.0,NaN,NaN,31.0,40.0,131.0
2,2,Alameda,2020-03-29,36.0,91.0,NaN,NaN,20.0,16.0,119.0
3,3,Siskiyou,2020-03-29,0.0,0.0,NaN,NaN,0.0,0.0,2.0
4,4,Del Norte,2020-03-29,1.0,2.0,NaN,NaN,0.0,0.0,3.0
5,5,Inyo,2020-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,El Dorado,2020-03-29,0.0,6.0,NaN,NaN,0.0,3.0,3.0
7,7,Sutter,2020-03-29,0.0,0.0,NaN,NaN,0.0,0.0,NaN
8,8,Nevada,2020-03-29,23.0,NaN,NaN,NaN,1.0,0.0,3.0
9,9,San Joaquin,2020-03-29,34.0,35.0,NaN,NaN,5.0,2.0,7.0
10,10,Riverside,2020-03-29,44.0,78.0,NaN,NaN,13.0,20.0,46.0
11,11,Stanislaus,2020-03-29,20.0,48.0,NaN,NaN,9.0,8.0,25.0
12,12,Lassen,2020-03-29,0.0,2.0,NaN,NaN,0.0,0.0,NaN
13,13,Imperial,2020-03-29,5.0,100.0,NaN,NaN,1.0,2.0,2.0
14,14,Calaveras,2020-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Mono,2020-03-29,0.0,1.0,NaN,NaN,0.0,0.0,2.0
16,16,Santa Barbara,2020-03-29,15.0,21.0,NaN,NaN,9.0,3.0,47.0
17,17,Plumas,2020-03-29,0.0,1.0,NaN,NaN,0.0,1.0,NaN
18,18,San Luis Obispo,2020-03-29,7.0,12.0,NaN,NaN,3.0,4.0,948.0
19,19,San Bernardino,2020-03-29,33.0,123.0,NaN,NaN,19.0,20.0,65.0
20,20,Monterey,2020-03-29,2.0,16.0,NaN,NaN,1.0,2.0,10.0
21,21,Merced,2020-03-29,1.0,7.0,NaN,NaN,0.0,0.0,3.0
22,22,Shasta,2020-03-29,0.0,0.0,NaN,NaN,0.0,0.0,NaN
23,23,Colusa,2020-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,Napa,2020-03-29,0.0,26.0,NaN,NaN,NaN,NaN,5.0
25,25,Fresno,2020-03-29,8.0,116.0,NaN,NaN,3.0,14.0,22.0
26,26,San Mateo,2020-03-29,46.0,27.0,NaN,NaN,16.0,10.0,28.0
27,27,Tehama,2020-03-29,0.0,0.0,NaN,NaN,0.0,0.0,2.0
28,28,Marin,2020-03-29,7.0,13.0,NaN,NaN,2.0,6.0,11.0
29,29,Solano,2020-03-29,7.0,27.0,NaN,NaN,4.0,1.0,28.0
...,...,...,...,...,...,...,...,...,...,...
13407,13407,Napa,2020-11-23,6.0,0.0,6.0,351.0,1.0,0.0,29.0
13408,13408,San Bernardino,2020-11-23,583.0,75.0,658.0,4082.0,140.0,11.0,80.0
13409,13409,Humboldt,2020-11-23,4.0,5.0,9.0,271.0,0.0,1.0,2.0
13410,13410,Mono,2020-11-23,1.0,0.0,1.0,17.0,0.0,0.0,2.0
13411,13411,Riverside,2020-11-23,420.0,78.0,498.0,3347.0,107.0,10.0,52.0
13412,13412,Del Norte,2020-11-23,1.0,0.0,1.0,52.0,0.0,0.0,2.0
13413,13413,Shasta,2020-11-23,48.0,0.0,48.0,561.0,7.0,0.0,5.0
13414,13414,Plumas,2020-11-23,0.0,0.0,0.0,35.0,0.0,0.0,0.0
13415,13415,Sonoma,2020-11-23,29.0,0.0,29.0,558.0,5.0,0.0,8.0
13416,13416,San Joaquin,2020-11-23,114.0,8.0,122.0,1036.0,32.0,3.0,30.0
13417,13417,Imperial,2020-11-23,51.0,1.0,52.0,265.0,15.0,0.0,4.0
13418,13418,Stanislaus,2020-11-23,156.0,9.0,165.0,1298.0,25.0,0.0,17.0
13419,13419,Lassen,2020-11-23,4.0,0.0,4.0,25.0,0.0,0.0,0.0
13420,13420,Tuolumne,2020-11-23,14.0,0.0,14.0,84.0,2.0,0.0,2.0
13421,13421,Nevada,2020-11-23,8.0,2.0,10.0,142.0,4.0,0.0,3.0
13422,13422,Orange,2020-11-23,463.0,80.0,543.0,5814.0,116.0,10.0,183.0
13423,13423,Contra Costa,2020-11-23,94.0,14.0,108.0,1564.0,25.0,1.0,50.0
13424,13424,Lake,2020-11-23,1.0,0.0,1.0,77.0,1.0,0.0,2.0
13425,13425,San Benito,2020-11-23,3.0,0.0,3.0,25.0,1.0,0.0,1.0
13426,13426,San Diego,2020-11-23,470.0,56.0,526.0,6797.0,140.0,12.0,245.0
13427,13427,Yolo,2020-11-23,20.0,0.0,20.0,96.0,7.0,0.0,8.0
13428,13428,Tulare,2020-11-23,56.0,12.0,68.0,679.0,8.0,1.0,24.0
13429,13429,Glenn,2020-11-23,0.0,0.0,0.0,47.0,0.0,0.0,0.0
13430,13430,Monterey,2020-11-23,64.0,2.0,66.0,717.0,13.0,2.0,23.0
13431,13431,Merced,2020-11-23,21.0,0.0,21.0,271.0,2.0,0.0,13.0
13432,13432,Mendocino,2020-11-23,12.0,0.0,12.0,177.0,5.0,0.0,5.0
13433,13433,Alameda,2020-11-23,123.0,26.0,149.0,2479.0,26.0,2.0,104.0
13434,13434,Butte,2020-11-23,32.0,0.0,32.0,453.0,4.0,0.0,14.0
13435,13435,Santa Cruz,2020-11-23,27.0,0.0,27.0,385.0,8.0,0.0,1.0
13436,13436,Yuba,2020-11-23,31.0,0.0,31.0,265.0,6.0,0.0,5.0

In [43]:
sql_statement = "select Homeless.DATE, sum(HOSPITALIZED_COVID_CONFIRMED_PATIENTS +  ROOM_OCCUPIED) as Total_Covid_Patients from Hospital left join Homeless on Hospital.COUNTY=Homeless.COUNTY group by Homeless.DATE order by Total_Covid_Patients"
df = pd.read_sql_query(sql_statement, conn)
display(df)

           DATE  Total_Covid_Patients
0    2020-04-23              212152.0
1    2020-04-25              224456.0
2    2020-04-26              224696.0
3    2020-04-27              226136.0
4    2020-04-28              227816.0
5    2020-04-29              228536.0
6    2020-05-01              229736.0
7    2020-05-02              231896.0
8    2020-04-30              232376.0
9    2020-05-03              232376.0
10   2020-05-04              246536.0
11   2020-05-05              248456.0
12   2020-05-11              248696.0
13   2020-05-12              249656.0
14   2020-05-16              249656.0
15   2020-05-06              250376.0
16   2020-05-18              250616.0
17   2020-05-08              251096.0
18   2020-05-10              251096.0
19   2020-05-09              251816.0
20   2020-05-15              252056.0
21   2020-05-19              252056.0
22   2020-05-13              252536.0
23   2020-05-14              253736.0
24   2020-05-17              253736.0
25   2020-05-07              254696.0
26   2020-05-20              254696.0
27   2020-05-21              257576.0
28   2020-05-22              263336.0
29   2020-05-23              265976.0
..          ...                   ...
137  2020-11-02              493016.0
138  2020-10-20              493496.0
139  2020-10-21              493496.0
140  2020-09-25              493736.0
141  2020-09-28              493736.0
142  2020-10-19              493736.0
143  2020-09-29              494456.0
144  2020-10-02              496136.0
145  2020-11-06              499256.0
146  2020-11-16              499976.0
147  2020-11-17              499976.0
148  2020-11-18              499976.0
149  2020-11-19              499976.0
150  2020-11-03              500696.0
151  2020-11-04              500696.0
152  2020-11-05              500696.0
153  2020-11-09              500696.0
154  2020-11-10              500696.0
155  2020-11-12              500696.0
156  2020-11-13              500696.0
157  2020-04-14             1324047.0
158  2020-04-15             1443807.0
159  2020-04-16             1695997.0
160  2020-04-17             1766691.0
161  2020-04-18             1777731.0
162  2020-04-19             1787811.0
163  2020-04-20             1794995.0
164  2020-04-21             1799691.0
165  2020-04-22             1884372.0
166  2020-04-24             2016710.0

[167 rows x 2 columns]

In [44]:
sql_statement = "select Hospital.COUNTY, sum(HOSPITALIZED_COVID_CONFIRMED_PATIENTS + ICU_COVID_CONFIRMED_PATIENTS + ROOM_OCCUPIED) as Total_Covid_Patients from Hospital left join Homeless on Hospital.COUNTY=Homeless.COUNTY group by Hospital.COUNTY order by Total_Covid_Patients desc LIMIT 32"
df = pd.read_sql_query(sql_statement, conn)
display(df)

            COUNTY  Total_Covid_Patients
0    San Francisco            66888335.0
1      Los Angeles             6157740.0
2        San Diego             1892920.0
3        Riverside             1523700.0
4          Alameda             1010980.0
5           Fresno              966220.0
6           Orange              876800.0
7      Santa Clara              869710.0
8          Ventura              816290.0
9   San Bernardino              779256.0
10      Sacramento              525080.0
11            Yolo              473250.0
12       San Mateo              334530.0
13           Butte              229422.0
14       Mendocino              217440.0
15          Sonoma              170320.0
16           Marin              150840.0
17          Placer              131000.0
18            Napa              102808.0
19      San Benito               76479.0
20      Santa Cruz               75050.0
21            Yuba               73380.0
22      Stanislaus               71594.0
23    Contra Costa               46758.0
24       Calaveras               40504.0
25          Sutter               35040.0
26        Humboldt               28440.0
27   Santa Barbara               21143.0
28          Merced               13177.0
29        Mariposa               12131.0
30          Madera                8971.0
31          Nevada                4595.0

In [50]:
sql_statement = "select Hospital.DATE, sum(HOSPITALIZED_SUSPECTED_COVID_PATIENTS + ICU_SUSPECTED_COVID_PATIENTS + TRAILERS_REQUESTED) as Estimated_Growing_Rate from Hospital left join Homeless on Hospital.COUNTY=Homeless.COUNTY group by Hospital.DATE order by Estimated_Growing_Rate desc"
df = pd.read_sql_query(sql_statement, conn)
display(df)

           DATE  Estimated_Growing_Rate
0    2020-03-30                 76993.0
1    2020-03-31                 76549.0
2    2020-04-07                 76489.0
3    2020-04-08                 75017.0
4    2020-04-01                 72618.0
5    2020-04-03                 70869.0
6    2020-04-02                 70701.0
7    2020-04-04                 69238.0
8    2020-04-05                 68746.0
9    2020-04-06                 67037.0
10   2020-03-29                 66296.0
11   2020-04-09                 61505.0
12   2020-04-11                 59840.0
13   2020-04-15                 59330.0
14   2020-04-10                 58239.0
15   2020-04-13                 55905.0
16   2020-04-12                 55069.0
17   2020-04-14                 54466.0
18   2020-04-21                 52802.0
19   2020-04-17                 51740.0
20   2020-05-26                 51709.0
21   2020-05-21                 51596.0
22   2020-04-16                 51523.0
23   2020-05-27                 49985.0
24   2020-05-28                 49684.0
25   2020-05-25                 49545.0
26   2020-05-20                 49360.0
27   2020-04-19                 49305.0
28   2020-04-18                 49004.0
29   2020-05-14                 48678.0
..          ...                     ...
210  2020-11-10                 36375.0
211  2020-11-20                 36297.0
212  2020-11-04                 36266.0
213  2020-11-23                 36165.0
214  2020-10-18                 36111.0
215  2020-11-03                 36083.0
216  2020-11-11                 36017.0
217  2020-11-09                 36004.0
218  2020-11-14                 35886.0
219  2020-10-16                 35876.0
220  2020-10-24                 35846.0
221  2020-10-23                 35709.0
222  2020-10-17                 35682.0
223  2020-11-05                 35679.0
224  2020-10-20                 35640.0
225  2020-11-07                 35620.0
226  2020-10-30                 35569.0
227  2020-11-15                 35536.0
228  2020-10-22                 35474.0
229  2020-11-13                 35409.0
230  2020-10-28                 35272.0
231  2020-10-31                 35260.0
232  2020-10-29                 35172.0
233  2020-10-26                 35167.0
234  2020-10-25                 35136.0
235  2020-11-08                 35060.0
236  2020-11-01                 35015.0
237  2020-11-06                 35000.0
238  2020-11-02                 34632.0
239  2020-10-27                 34563.0

[240 rows x 2 columns]

In [55]:
sql_statement = "select Hospital.COUNTY, Hospital.DATE, sum(HOSPITALIZED_COVID_CONFIRMED_PATIENTS + ICU_COVID_CONFIRMED_PATIENTS + ROOM_OCCUPIED) as Total_Covid_Patients, sum(HOSPITALIZED_SUSPECTED_COVID_PATIENTS + ICU_SUSPECTED_COVID_PATIENTS + TRAILERS_REQUESTED) as Estimated_Growing_Rate from Hospital left join Homeless on Hospital.COUNTY=Homeless.COUNTY group by Hospital.DATE order by Total_Covid_Patients desc"
df = pd.read_sql_query(sql_statement, conn)
display(df)

              COUNTY        DATE  Total_Covid_Patients  Estimated_Growing_Rate
0      San Francisco  2020-07-28              391013.0                 44791.0
1             Shasta  2020-07-29              390721.0                 43733.0
2             Nevada  2020-07-21              390509.0                 47360.0
3          Calaveras  2020-07-20              389451.0                 44699.0
4            Alameda  2020-07-27              388741.0                 44242.0
5               Napa  2020-07-19              388583.0                 44698.0
6              Butte  2020-07-26              388575.0                 45825.0
7             Fresno  2020-07-23              388062.0                 45452.0
8          Riverside  2020-07-30              387937.0                 43127.0
9    San Luis Obispo  2020-07-18              387379.0                 44793.0
10    San Bernardino  2020-07-24              387226.0                 45392.0
11             Butte  2020-07-15              386982.0                 45026.0
12           Alameda  2020-07-14              386824.0                 45185.0
13              Mono  2020-07-25              386805.0                 46553.0
14           Ventura  2020-07-22              386676.0                 44511.0
15            Colusa  2020-07-17              386489.0                 45322.0
16            Orange  2020-07-16              386462.0                 46057.0
17         Del Norte  2020-07-13              386330.0                 44238.0
18           Trinity  2020-07-31              385899.0                 42362.0
19          Siskiyou  2020-08-01              385437.0                 42737.0
20             Kings  2020-08-02              382973.0                 41163.0
21              Kern  2020-07-12              382795.0                 43885.0
22            Fresno  2020-08-03              381087.0                 42694.0
23     San Francisco  2020-07-11              381057.0                 45702.0
24             Modoc  2020-07-10              380771.0                 45995.0
25       San Joaquin  2020-08-04              380231.0                 42141.0
26          Tuolumne  2020-07-09              378471.0                 47482.0
27         San Diego  2020-07-07              376985.0                 45975.0
28            Tulare  2020-07-08              376919.0                 46731.0
29          Humboldt  2020-08-05              376611.0                 42864.0
..               ...         ...                   ...                     ...
210           Placer  2020-10-03              333582.0                 37397.0
211       Sacramento  2020-10-06              333325.0                 37593.0
212         Imperial  2020-10-07              332888.0                 37649.0
213        El Dorado  2020-11-01              332729.0                 35015.0
214           Sonoma  2020-10-08              331963.0                 37075.0
215      Santa Clara  2020-10-30              331384.0                 35569.0
216          Alameda  2020-10-29              331057.0                 35172.0
217         Humboldt  2020-10-31              331046.0                 35260.0
218          Alameda  2020-03-30              330574.0                 76993.0
219            Butte  2020-10-09              329945.0                 37209.0
220      Los Angeles  2020-10-28              329924.0                 35272.0
221           Tulare  2020-10-10              329206.0                 37170.0
222           Plumas  2020-10-27              329038.0                 34563.0
223           Amador  2020-10-26              328522.0                 35167.0
224           Orange  2020-10-21              328460.0                 37090.0
225            Kings  2020-10-19              328455.0                 37132.0
226      Los Angeles  2020-10-12              328409.0                 36688.0
227       San Benito  2020-10-23              328200.0                 35709.0
228            Modoc  2020-10-22              328144.0                 35474.0
229             Yolo  2020-10-20              328100.0                 35640.0
230          Trinity  2020-10-18              328045.0                 36111.0
231       San Benito  2020-10-25              327893.0                 35136.0
232        Mendocino  2020-10-13              327804.0                 37250.0
233           Plumas  2020-10-17              327786.0                 35682.0
234            Kings  2020-10-11              327758.0                 37058.0
235          Trinity  2020-10-14              327283.0                 37222.0
236            Modoc  2020-10-24              326971.0                 35846.0
237            Marin  2020-10-15              326814.0                 36995.0
238           Shasta  2020-10-16              326757.0                 35876.0
239        Mendocino  2020-03-29              325121.0                 66296.0

[240 rows x 4 columns]